### PR TITLE
Updated amazon adapter to use v3 credentials and settings

### PR DESCRIPTION
**Pull request by TimVroom**
Amazon uses a new sdk/api version. This update works with it.

### CODE REVIEW

**Comment by lilmuckers** [comment]
Looks good to me. Not sure about the change of use from constants to just strings, but not unsure enough to really make any issue on it :)

**Comment by TimVroom** [comment]
Agreed on the strings instead of constants, but i could not find the constants anywhere in the amazon sdk classes. So had to resort to string.

**Comment by lilmuckers** [comment]
That's fair - SQS seems to be the primary use case for this module from everything i've seen - so i'm happy to include this update.
(i find this interesting because i never did full on production testing of SQS due to primarily working on non-AWS infrastructure in my magento career :) )

**Comment by TimVroom** [comment]
Full production test of this will happen pretty shortly for this project im using it on. If it gives errors, i'll let you know what it is.

**Pull request merged**
